// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalAdminResDao is internal type for wrapping internal DAO implements.
type internalAdminResDao = *internal.AdminResDao

// adminResDao is the data access object for table admin_res.
// You can define custom methods on it to extend its functionality as you wish.
type adminResDao struct {
	internalAdminResDao
}

var (
	// AdminRes is globally public accessible object for table admin_res operations.
	AdminRes = adminResDao{
		internal.NewAdminResDao(),
	}
)

// Fill with you ideas below.
