// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalAdminUserRoleDao is internal type for wrapping internal DAO implements.
type internalAdminUserRoleDao = *internal.AdminUserRoleDao

// adminUserRoleDao is the data access object for table admin_user_role.
// You can define custom methods on it to extend its functionality as you wish.
type adminUserRoleDao struct {
	internalAdminUserRoleDao
}

var (
	// AdminUserRole is globally public accessible object for table admin_user_role operations.
	AdminUserRole = adminUserRoleDao{
		internal.NewAdminUserRoleDao(),
	}
)

// Fill with you ideas below.
