// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalAdminRoleResDao is internal type for wrapping internal DAO implements.
type internalAdminRoleResDao = *internal.AdminRoleResDao

// adminRoleResDao is the data access object for table admin_role_res.
// You can define custom methods on it to extend its functionality as you wish.
type adminRoleResDao struct {
	internalAdminRoleResDao
}

var (
	// AdminRoleRes is globally public accessible object for table admin_role_res operations.
	AdminRoleRes = adminRoleResDao{
		internal.NewAdminRoleResDao(),
	}
)

// Fill with you ideas below.
