// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTAdDao is internal type for wrapping internal DAO implements.
type internalTAdDao = *internal.TAdDao

// tAdDao is the data access object for table t_ad.
// You can define custom methods on it to extend its functionality as you wish.
type tAdDao struct {
	internalTAdDao
}

var (
	// TAd is globally public accessible object for table t_ad operations.
	TAd = tAdDao{
		internal.NewTAdDao(),
	}
)

// Fill with you ideas below.
