// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTAdSlotDao is internal type for wrapping internal DAO implements.
type internalTAdSlotDao = *internal.TAdSlotDao

// tAdSlotDao is the data access object for table t_ad_slot.
// You can define custom methods on it to extend its functionality as you wish.
type tAdSlotDao struct {
	internalTAdSlotDao
}

var (
	// TAdSlot is globally public accessible object for table t_ad_slot operations.
	TAdSlot = tAdSlotDao{
		internal.NewTAdSlotDao(),
	}
)

// Fill with you ideas below.
