// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTAdGiftDao is internal type for wrapping internal DAO implements.
type internalTAdGiftDao = *internal.TAdGiftDao

// tAdGiftDao is the data access object for table t_ad_gift.
// You can define custom methods on it to extend its functionality as you wish.
type tAdGiftDao struct {
	internalTAdGiftDao
}

var (
	// TAdGift is globally public accessible object for table t_ad_gift operations.
	TAdGift = tAdGiftDao{
		internal.NewTAdGiftDao(),
	}
)

// Fill with you ideas below.
