// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTAppStoreDao is an internal type for wrapping the internal DAO implementation.
type internalTAppStoreDao = *internal.TAppStoreDao

// tAppStoreDao is the data access object for the table t_app_store.
// You can define custom methods on it to extend its functionality as needed.
type tAppStoreDao struct {
	internalTAppStoreDao
}

var (
	// TAppStore is a globally accessible object for table t_app_store operations.
	TAppStore = tAppStoreDao{
		internal.NewTAppStoreDao(),
	}
)

// Add your custom methods and functionality below.
