// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTAppVersionDao is internal type for wrapping internal DAO implements.
type internalTAppVersionDao = *internal.TAppVersionDao

// tAppVersionDao is the data access object for table t_app_version.
// You can define custom methods on it to extend its functionality as you wish.
type tAppVersionDao struct {
	internalTAppVersionDao
}

var (
	// TAppVersion is globally public accessible object for table t_app_version operations.
	TAppVersion = tAppVersionDao{
		internal.NewTAppVersionDao(),
	}
)

// Fill with you ideas below.
