// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTChannelRegistrationPayDailyDao is an internal type for wrapping the internal DAO implementation.
type internalTChannelRegistrationPayDailyDao = *internal.TChannelRegistrationPayDailyDao

// tChannelRegistrationPayDailyDao is the data access object for the table t_channel_registration_pay_daily.
// You can define custom methods on it to extend its functionality as needed.
type tChannelRegistrationPayDailyDao struct {
	internalTChannelRegistrationPayDailyDao
}

var (
	// TChannelRegistrationPayDaily is a globally accessible object for table t_channel_registration_pay_daily operations.
	TChannelRegistrationPayDaily = tChannelRegistrationPayDailyDao{
		internal.NewTChannelRegistrationPayDailyDao(),
	}
)

// Add your custom methods and functionality below.
