// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTChannelDao is internal type for wrapping internal DAO implements.
type internalTChannelDao = *internal.TChannelDao

// tChannelDao is the data access object for table t_channel.
// You can define custom methods on it to extend its functionality as you wish.
type tChannelDao struct {
	internalTChannelDao
}

var (
	// TChannel is globally public accessible object for table t_channel operations.
	TChannel = tChannelDao{
		internal.NewTChannelDao(),
	}
)

// Fill with you ideas below.
