// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTChannelRetaindDailyDao is an internal type for wrapping the internal DAO implementation.
type internalTChannelRetaindDailyDao = *internal.TChannelRetaindDailyDao

// tChannelRetaindDailyDao is the data access object for the table t_channel_retaind_daily.
// You can define custom methods on it to extend its functionality as needed.
type tChannelRetaindDailyDao struct {
	internalTChannelRetaindDailyDao
}

var (
	// TChannelRetaindDaily is a globally accessible object for table t_channel_retaind_daily operations.
	TChannelRetaindDaily = tChannelRetaindDailyDao{
		internal.NewTChannelRetaindDailyDao(),
	}
)

// Add your custom methods and functionality below.
