// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTChannelRechargeRenewalsMonthlyDao is an internal type for wrapping the internal DAO implementation.
type internalTChannelRechargeRenewalsMonthlyDao = *internal.TChannelRechargeRenewalsMonthlyDao

// tChannelRechargeRenewalsMonthlyDao is the data access object for the table t_channel_recharge_renewals_monthly.
// You can define custom methods on it to extend its functionality as needed.
type tChannelRechargeRenewalsMonthlyDao struct {
	internalTChannelRechargeRenewalsMonthlyDao
}

var (
	// TChannelRechargeRenewalsMonthly is a globally accessible object for table t_channel_recharge_renewals_monthly operations.
	TChannelRechargeRenewalsMonthly = tChannelRechargeRenewalsMonthlyDao{
		internal.NewTChannelRechargeRenewalsMonthlyDao(),
	}
)

// Add your custom methods and functionality below.
