// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTCountryDao is internal type for wrapping internal DAO implements.
type internalTCountryDao = *internal.TCountryDao

// tCountryDao is the data access object for table t_country.
// You can define custom methods on it to extend its functionality as you wish.
type tCountryDao struct {
	internalTCountryDao
}

var (
	// TCountry is globally public accessible object for table t_country operations.
	TCountry = tCountryDao{
		internal.NewTCountryDao(),
	}
)

// Fill with you ideas below.
