// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTDailyPaymentTotalByChannelDao is an internal type for wrapping the internal DAO implementation.
type internalTDailyPaymentTotalByChannelDao = *internal.TDailyPaymentTotalByChannelDao

// tDailyPaymentTotalByChannelDao is the data access object for the table t_daily_payment_total_by_channel.
// You can define custom methods on it to extend its functionality as needed.
type tDailyPaymentTotalByChannelDao struct {
	internalTDailyPaymentTotalByChannelDao
}

var (
	// TDailyPaymentTotalByChannel is a globally accessible object for table t_daily_payment_total_by_channel operations.
	TDailyPaymentTotalByChannel = tDailyPaymentTotalByChannelDao{
		internal.NewTDailyPaymentTotalByChannelDao(),
	}
)

// Add your custom methods and functionality below.
