// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTDailyAdStatisticsDao is an internal type for wrapping the internal DAO implementation.
type internalTDailyAdStatisticsDao = *internal.TDailyAdStatisticsDao

// tDailyAdStatisticsDao is the data access object for the table t_daily_ad_statistics.
// You can define custom methods on it to extend its functionality as needed.
type tDailyAdStatisticsDao struct {
	internalTDailyAdStatisticsDao
}

var (
	// TDailyAdStatistics is a globally accessible object for table t_daily_ad_statistics operations.
	TDailyAdStatistics = tDailyAdStatisticsDao{
		internal.NewTDailyAdStatisticsDao(),
	}
)

// Add your custom methods and functionality below.
