// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTDevDao is internal type for wrapping internal DAO implements.
type internalTDevDao = *internal.TDevDao

// tDevDao is the data access object for table t_dev.
// You can define custom methods on it to extend its functionality as you wish.
type tDevDao struct {
	internalTDevDao
}

var (
	// TDev is globally public accessible object for table t_dev operations.
	TDev = tDevDao{
		internal.NewTDevDao(),
	}
)

// Fill with you ideas below.
