// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTDictDao is internal type for wrapping internal DAO implements.
type internalTDictDao = *internal.TDictDao

// tDictDao is the data access object for table t_dict.
// You can define custom methods on it to extend its functionality as you wish.
type tDictDao struct {
	internalTDictDao
}

var (
	// TDict is globally public accessible object for table t_dict operations.
	TDict = tDictDao{
		internal.NewTDictDao(),
	}
)

// Fill with you ideas below.
