// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTDocDao is internal type for wrapping internal DAO implements.
type internalTDocDao = *internal.TDocDao

// tDocDao is the data access object for table t_doc.
// You can define custom methods on it to extend its functionality as you wish.
type tDocDao struct {
	internalTDocDao
}

var (
	// TDoc is globally public accessible object for table t_doc operations.
	TDoc = tDocDao{
		internal.NewTDocDao(),
	}
)

// Fill with you ideas below.
