// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTGiftDao is internal type for wrapping internal DAO implements.
type internalTGiftDao = *internal.TGiftDao

// tGiftDao is the data access object for table t_gift.
// You can define custom methods on it to extend its functionality as you wish.
type tGiftDao struct {
	internalTGiftDao
}

var (
	// TGift is globally public accessible object for table t_gift operations.
	TGift = tGiftDao{
		internal.NewTGiftDao(),
	}
)

// Fill with you ideas below.
