// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTGoodsDao is internal type for wrapping internal DAO implements.
type internalTGoodsDao = *internal.TGoodsDao

// tGoodsDao is the data access object for table t_goods.
// You can define custom methods on it to extend its functionality as you wish.
type tGoodsDao struct {
	internalTGoodsDao
}

var (
	// TGoods is globally public accessible object for table t_goods operations.
	TGoods = tGoodsDao{
		internal.NewTGoodsDao(),
	}
)

// Fill with you ideas below.
