// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTIosAccountDao is internal type for wrapping internal DAO implements.
type internalTIosAccountDao = *internal.TIosAccountDao

// tIosAccountDao is the data access object for table t_ios_account.
// You can define custom methods on it to extend its functionality as you wish.
type tIosAccountDao struct {
	internalTIosAccountDao
}

var (
	// TIosAccount is globally public accessible object for table t_ios_account operations.
	TIosAccount = tIosAccountDao{
		internal.NewTIosAccountDao(),
	}
)

// Fill with you ideas below.
