// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTNodeDao is internal type for wrapping internal DAO implements.
type internalTNodeDao = *internal.TNodeDao

// tNodeDao is the data access object for table t_node.
// You can define custom methods on it to extend its functionality as you wish.
type tNodeDao struct {
	internalTNodeDao
}

var (
	// TNode is globally public accessible object for table t_node operations.
	TNode = tNodeDao{
		internal.NewTNodeDao(),
	}
)

// Fill with you ideas below.
