// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTNodeDnsDao is internal type for wrapping internal DAO implements.
type internalTNodeDnsDao = *internal.TNodeDnsDao

// tNodeDnsDao is the data access object for table t_node_dns.
// You can define custom methods on it to extend its functionality as you wish.
type tNodeDnsDao struct {
	internalTNodeDnsDao
}

var (
	// TNodeDns is globally public accessible object for table t_node_dns operations.
	TNodeDns = tNodeDnsDao{
		internal.NewTNodeDnsDao(),
	}
)

// Fill with you ideas below.
