// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTNodeUuidDao is internal type for wrapping internal DAO implements.
type internalTNodeUuidDao = *internal.TNodeUuidDao

// tNodeUuidDao is the data access object for table t_node_uuid.
// You can define custom methods on it to extend its functionality as you wish.
type tNodeUuidDao struct {
	internalTNodeUuidDao
}

var (
	// TNodeUuid is globally public accessible object for table t_node_uuid operations.
	TNodeUuid = tNodeUuidDao{
		internal.NewTNodeUuidDao(),
	}
)

// Fill with you ideas below.
