// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTNoticeDao is internal type for wrapping internal DAO implements.
type internalTNoticeDao = *internal.TNoticeDao

// tNoticeDao is the data access object for table t_notice.
// You can define custom methods on it to extend its functionality as you wish.
type tNoticeDao struct {
	internalTNoticeDao
}

var (
	// TNotice is globally public accessible object for table t_notice operations.
	TNotice = tNoticeDao{
		internal.NewTNoticeDao(),
	}
)

// Fill with you ideas below.
