// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTPaymentChannelsDao is internal type for wrapping internal DAO implements.
type internalTPaymentChannelsDao = *internal.TPaymentChannelsDao

// tPaymentChannelsDao is the data access object for table t_payment_channels.
// You can define custom methods on it to extend its functionality as you wish.
type tPaymentChannelsDao struct {
	internalTPaymentChannelsDao
}

var (
	// TPaymentChannels is globally public accessible object for table t_payment_channels operations.
	TPaymentChannels = tPaymentChannelsDao{
		internal.NewTPaymentChannelsDao(),
	}
)

// Fill with you ideas below.
