// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTPromotionDnsDao is an internal type for wrapping the internal DAO implementation.
type internalTPromotionDnsDao = *internal.TPromotionDnsDao

// tPromotionDnsDao is the data access object for the table t_promotion_dns.
// You can define custom methods on it to extend its functionality as needed.
type tPromotionDnsDao struct {
	internalTPromotionDnsDao
}

var (
	// TPromotionDns is a globally accessible object for table t_promotion_dns operations.
	TPromotionDns = tPromotionDnsDao{
		internal.NewTPromotionDnsDao(),
	}
)

// Add your custom methods and functionality below.
