// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTServingCountryDao is internal type for wrapping internal DAO implements.
type internalTServingCountryDao = *internal.TServingCountryDao

// tServingCountryDao is the data access object for table t_serving_country.
// You can define custom methods on it to extend its functionality as you wish.
type tServingCountryDao struct {
	internalTServingCountryDao
}

var (
	// TServingCountry is globally public accessible object for table t_serving_country operations.
	TServingCountry = tServingCountryDao{
		internal.NewTServingCountryDao(),
	}
)

// Fill with you ideas below.
