// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTSiteDao is internal type for wrapping internal DAO implements.
type internalTSiteDao = *internal.TSiteDao

// tSiteDao is the data access object for table t_site.
// You can define custom methods on it to extend its functionality as you wish.
type tSiteDao struct {
	internalTSiteDao
}

var (
	// TSite is globally public accessible object for table t_site operations.
	TSite = tSiteDao{
		internal.NewTSiteDao(),
	}
)

// Fill with you ideas below.
