// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTSuccessRecordDao is internal type for wrapping internal DAO implements.
type internalTSuccessRecordDao = *internal.TSuccessRecordDao

// tSuccessRecordDao is the data access object for table t_success_record.
// You can define custom methods on it to extend its functionality as you wish.
type tSuccessRecordDao struct {
	internalTSuccessRecordDao
}

var (
	// TSuccessRecord is globally public accessible object for table t_success_record operations.
	TSuccessRecord = tSuccessRecordDao{
		internal.NewTSuccessRecordDao(),
	}
)

// Fill with you ideas below.
