// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTTaskDao is internal type for wrapping internal DAO implements.
type internalTTaskDao = *internal.TTaskDao

// tTaskDao is the data access object for table t_task.
// You can define custom methods on it to extend its functionality as you wish.
type tTaskDao struct {
	internalTTaskDao
}

var (
	// TTask is globally public accessible object for table t_task operations.
	TTask = tTaskDao{
		internal.NewTTaskDao(),
	}
)

// Fill with you ideas below.
