// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTUploadLogDao is internal type for wrapping internal DAO implements.
type internalTUploadLogDao = *internal.TUploadLogDao

// tUploadLogDao is the data access object for table t_upload_log.
// You can define custom methods on it to extend its functionality as you wish.
type tUploadLogDao struct {
	internalTUploadLogDao
}

var (
	// TUploadLog is globally public accessible object for table t_upload_log operations.
	TUploadLog = tUploadLogDao{
		internal.NewTUploadLogDao(),
	}
)

// Fill with you ideas below.
