// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTUserReportMonthlyDao is internal type for wrapping internal DAO implements.
type internalTUserReportMonthlyDao = *internal.TUserReportMonthlyDao

// tUserReportMonthlyDao is the data access object for table t_user_report_monthly.
// You can define custom methods on it to extend its functionality as you wish.
type tUserReportMonthlyDao struct {
	internalTUserReportMonthlyDao
}

var (
	// TUserReportMonthly is globally public accessible object for table t_user_report_monthly operations.
	TUserReportMonthly = tUserReportMonthlyDao{
		internal.NewTUserReportMonthlyDao(),
	}
)

// Fill with you ideas below.
