// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTUserAdLogDao is internal type for wrapping internal DAO implements.
type internalTUserAdLogDao = *internal.TUserAdLogDao

// tUserAdLogDao is the data access object for table t_user_ad_log.
// You can define custom methods on it to extend its functionality as you wish.
type tUserAdLogDao struct {
	internalTUserAdLogDao
}

var (
	// TUserAdLog is globally public accessible object for table t_user_ad_log operations.
	TUserAdLog = tUserAdLogDao{
		internal.NewTUserAdLogDao(),
	}
)

// Fill with you ideas below.
