// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTUserTrafficDao is internal type for wrapping internal DAO implements.
type internalTUserTrafficDao = *internal.TUserTrafficDao

// tUserTrafficDao is the data access object for table t_user_traffic.
// You can define custom methods on it to extend its functionality as you wish.
type tUserTrafficDao struct {
	internalTUserTrafficDao
}

var (
	// TUserTraffic is globally public accessible object for table t_user_traffic operations.
	TUserTraffic = tUserTrafficDao{
		internal.NewTUserTrafficDao(),
	}
)

// Fill with you ideas below.
