// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTUserNodeDao is internal type for wrapping internal DAO implements.
type internalTUserNodeDao = *internal.TUserNodeDao

// tUserNodeDao is the data access object for table t_user_node.
// You can define custom methods on it to extend its functionality as you wish.
type tUserNodeDao struct {
	internalTUserNodeDao
}

var (
	// TUserNode is globally public accessible object for table t_user_node operations.
	TUserNode = tUserNodeDao{
		internal.NewTUserNodeDao(),
	}
)

// Fill with you ideas below.
