// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTUserCancelledDao is internal type for wrapping internal DAO implements.
type internalTUserCancelledDao = *internal.TUserCancelledDao

// tUserCancelledDao is the data access object for table t_user_cancelled.
// You can define custom methods on it to extend its functionality as you wish.
type tUserCancelledDao struct {
	internalTUserCancelledDao
}

var (
	// TUserCancelled is globally public accessible object for table t_user_cancelled operations.
	TUserCancelled = tUserCancelledDao{
		internal.NewTUserCancelledDao(),
	}
)

// Fill with you ideas below.
