// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTUserConfigDao is internal type for wrapping internal DAO implements.
type internalTUserConfigDao = *internal.TUserConfigDao

// tUserConfigDao is the data access object for table t_user_config.
// You can define custom methods on it to extend its functionality as you wish.
type tUserConfigDao struct {
	internalTUserConfigDao
}

var (
	// TUserConfig is globally public accessible object for table t_user_config operations.
	TUserConfig = tUserConfigDao{
		internal.NewTUserConfigDao(),
	}
)

// Fill with you ideas below.
