// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTUserRechargeReportDayDao is internal type for wrapping internal DAO implements.
type internalTUserRechargeReportDayDao = *internal.TUserRechargeReportDayDao

// tUserRechargeReportDayDao is the data access object for table t_user_recharge_report_day.
// You can define custom methods on it to extend its functionality as you wish.
type tUserRechargeReportDayDao struct {
	internalTUserRechargeReportDayDao
}

var (
	// TUserRechargeReportDay is globally public accessible object for table t_user_recharge_report_day operations.
	TUserRechargeReportDay = tUserRechargeReportDayDao{
		internal.NewTUserRechargeReportDayDao(),
	}
)

// Fill with you ideas below.
