// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTUserDevDao is internal type for wrapping internal DAO implements.
type internalTUserDevDao = *internal.TUserDevDao

// tUserDevDao is the data access object for table t_user_dev.
// You can define custom methods on it to extend its functionality as you wish.
type tUserDevDao struct {
	internalTUserDevDao
}

var (
	// TUserDev is globally public accessible object for table t_user_dev operations.
	TUserDev = tUserDevDao{
		internal.NewTUserDevDao(),
	}
)

// Fill with you ideas below.
