// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTUserDeviceDao is internal type for wrapping internal DAO implements.
type internalTUserDeviceDao = *internal.TUserDeviceDao

// tUserDeviceDao is the data access object for table t_user_device.
// You can define custom methods on it to extend its functionality as you wish.
type tUserDeviceDao struct {
	internalTUserDeviceDao
}

var (
	// TUserDevice is globally public accessible object for table t_user_device operations.
	TUserDevice = tUserDeviceDao{
		internal.NewTUserDeviceDao(),
	}
)

// Fill with you ideas below.
