// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTUserVipAttrRecordsDao is internal type for wrapping internal DAO implements.
type internalTUserVipAttrRecordsDao = *internal.TUserVipAttrRecordsDao

// tUserVipAttrRecordsDao is the data access object for table t_user_vip_attr_records.
// You can define custom methods on it to extend its functionality as you wish.
type tUserVipAttrRecordsDao struct {
	internalTUserVipAttrRecordsDao
}

var (
	// TUserVipAttrRecords is globally public accessible object for table t_user_vip_attr_records operations.
	TUserVipAttrRecords = tUserVipAttrRecordsDao{
		internal.NewTUserVipAttrRecordsDao(),
	}
)

// Fill with you ideas below.
