// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTUserOpLogDao is internal type for wrapping internal DAO implements.
type internalTUserOpLogDao = *internal.TUserOpLogDao

// tUserOpLogDao is the data access object for table t_user_op_log.
// You can define custom methods on it to extend its functionality as you wish.
type tUserOpLogDao struct {
	internalTUserOpLogDao
}

var (
	// TUserOpLog is globally public accessible object for table t_user_op_log operations.
	TUserOpLog = tUserOpLogDao{
		internal.NewTUserOpLogDao(),
	}
)

// Fill with you ideas below.
