// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTUserVipAttrRecordDao is internal type for wrapping internal DAO implements.
type internalTUserVipAttrRecordDao = *internal.TUserVipAttrRecordDao

// tUserVipAttrRecordDao is the data access object for table t_user_vip_attr_record.
// You can define custom methods on it to extend its functionality as you wish.
type tUserVipAttrRecordDao struct {
	internalTUserVipAttrRecordDao
}

var (
	// TUserVipAttrRecord is globally public accessible object for table t_user_vip_attr_record operations.
	TUserVipAttrRecord = tUserVipAttrRecordDao{
		internal.NewTUserVipAttrRecordDao(),
	}
)

// Fill with you ideas below.
