// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTUserTeamDao is internal type for wrapping internal DAO implements.
type internalTUserTeamDao = *internal.TUserTeamDao

// tUserTeamDao is the data access object for table t_user_team.
// You can define custom methods on it to extend its functionality as you wish.
type tUserTeamDao struct {
	internalTUserTeamDao
}

var (
	// TUserTeam is globally public accessible object for table t_user_team operations.
	TUserTeam = tUserTeamDao{
		internal.NewTUserTeamDao(),
	}
)

// Fill with you ideas below.
