// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTV2RayUserTrafficDao is internal type for wrapping internal DAO implements.
type internalTV2RayUserTrafficDao = *internal.TV2RayUserTrafficDao

// tV2RayUserTrafficDao is the data access object for table t_v2ray_user_traffic.
// You can define custom methods on it to extend its functionality as you wish.
type tV2RayUserTrafficDao struct {
	internalTV2RayUserTrafficDao
}

var (
	// TV2RayUserTraffic is globally public accessible object for table t_v2ray_user_traffic operations.
	TV2RayUserTraffic = tV2RayUserTrafficDao{
		internal.NewTV2RayUserTrafficDao(),
	}
)

// Fill with you ideas below.
