// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTV2RayUserTrafficLogDao is internal type for wrapping internal DAO implements.
type internalTV2RayUserTrafficLogDao = *internal.TV2RayUserTrafficLogDao

// tV2RayUserTrafficLogDao is the data access object for table t_v2ray_user_traffic_log.
// You can define custom methods on it to extend its functionality as you wish.
type tV2RayUserTrafficLogDao struct {
	internalTV2RayUserTrafficLogDao
}

var (
	// TV2RayUserTrafficLog is globally public accessible object for table t_v2ray_user_traffic_log operations.
	TV2RayUserTrafficLog = tV2RayUserTrafficLogDao{
		internal.NewTV2RayUserTrafficLogDao(),
	}
)

// Fill with you ideas below.
