// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTWorkLogDao is internal type for wrapping internal DAO implements.
type internalTWorkLogDao = *internal.TWorkLogDao

// tWorkLogDao is the data access object for table t_work_log.
// You can define custom methods on it to extend its functionality as you wish.
type tWorkLogDao struct {
	internalTWorkLogDao
}

var (
	// TWorkLog is globally public accessible object for table t_work_log operations.
	TWorkLog = tWorkLogDao{
		internal.NewTWorkLogDao(),
	}
)

// Fill with you ideas below.
