// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/dao/internal"
)

// internalTWorkModeDao is internal type for wrapping internal DAO implements.
type internalTWorkModeDao = *internal.TWorkModeDao

// tWorkModeDao is the data access object for table t_work_mode.
// You can define custom methods on it to extend its functionality as you wish.
type tWorkModeDao struct {
	internalTWorkModeDao
}

var (
	// TWorkMode is globally public accessible object for table t_work_mode operations.
	TWorkMode = tWorkModeDao{
		internal.NewTWorkModeDao(),
	}
)

// Fill with you ideas below.
