// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/service/orm/dao/internal"
)

// internalTUserReportDayDao is internal type for wrapping internal DAO implements.
type internalTUserReportDayDao = *internal.TUserReportDayDao

// tUserReportDayDao is the data access object for table t_user_report_day.
// You can define custom methods on it to extend its functionality as you wish.
type tUserReportDayDao struct {
	internalTUserReportDayDao
}

var (
	// TUserReportDay is globally public accessible object for table t_user_report_day operations.
	TUserReportDay = tUserReportDayDao{
		internal.NewTUserReportDayDao(),
	}
)

// Fill with you ideas below.
