// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-speed/service/orm/dao/internal"
)

// internalTUserOnlineDayDao is internal type for wrapping internal DAO implements.
type internalTUserOnlineDayDao = *internal.TUserOnlineDayDao

// tUserOnlineDayDao is the data access object for table t_user_online_day.
// You can define custom methods on it to extend its functionality as you wish.
type tUserOnlineDayDao struct {
	internalTUserOnlineDayDao
}

var (
	// TUserOnlineDay is globally public accessible object for table t_user_online_day operations.
	TUserOnlineDay = tUserOnlineDayDao{
		internal.NewTUserOnlineDayDao(),
	}
)

// Fill with you ideas below.
