speed-db:
  host: 127.0.0.1
  port: 3306
  user: speed
  pswd: IUY*&^*^!12312HGJHG886!32
  db: speed
  charset: utf8

report-speed-db:
  host: 127.0.0.1
  port: 3306
  user: speed
  pswd: IUY*&^*^!12312HGJHG886!32
  db: speed_report
  charset: utf8