system:
  env: debug
  addr: 13003
  show-sql: true
  file_link: "http://localhost:13005"
  fs_site: "http://localhost:16002"
  admin_address: "http://localhost:13001"
db:
  host: localhost
  user: root
  password: 123456
  db-name: speed
  port: 3306
  log:
    level: info
    adapter: console
    path: ./logs/go-executor.log
    reverse-days: 7
log:
  level: info
  adapter: console
  path: ./logs/go-executor.log
  reverse-days: 7
redis:
  addr: localhost:6379
  password: 269423f39abf0d0ac
  db: 1
kafka:
  addr:
    - localhost:9092

