system:
  env: debug
  addr: 13001
  show-sql: true
  file_link: "http://localhost:13005"
  fs_site: "http://localhost:16002"


log:
  level: info
  adapter: console
  path: ./logs/go-admin.log
  reverse-days: 7
redis:
  addr:
  password:
  db: 1
kafka:
  addr:
    - localhost:9092

